# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
            ],
        ),
    ]
