# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Product comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.Product', verbose_name='To product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to='product.Product', verbose_name='To product')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='To user')),
            ],
        ),
    ]
